
<h3>Listar Funcionário</h3>
<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">CPF</th>
      <th scope="col">Salário</th>
      <th scope="col">Editar</th>
      <th scope="col">Excluir</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($this->lista as $f): ?>
    <tr>
        <td><?php echo $f->getNome(); ?></td>
        <td><?php echo $f->getCpf(); ?></td>
        <td><?php echo $f->getSalario(); ?></td>
        <td>
            <a href="<?php echo $this->url('rota2', array(
                'action' => 'editar', 'id' => $f->getId()
            )); ?>">
                Editar</a></td>
        <td>
            <a href="<?php echo $this->url('rota2', array(
                'action' => 'excluir', 'id' => $f->getId()
            )); ?>">
                Excluir</a></td>
    </tr>
    <?php endforeach; ?>

  </tbody>
</table>

<br>
<a class="btn btn-primary" href="<?php echo $this->url('home'); ?>" role="button">Voltar</a>
<br>